export const ADD_TO_CART = "ADD_TO_CART";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const UPDATE_ITEM_QTY_IN_CART = "UPDATE_ITEM_QTY_IN_CART"; 
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";