import cp from "child_process";
// console.log("Try to open Calculator...");
// cp.execSync("calc");
// console.log("Try to open code editor");
// cp.execSync("code");
import os from "os";
// console.log(os.platform());
// console.log(os.cpus());
// console.log(os.homedir());
// console.log(os.userInfo());
import fs from "fs";
// let buffer = fs.readFileSync("abc.txt"); 
// console.log(buffer);
import chalk from "chalk";
import figlet from "figlet";
// console.log(chalk.blackBright("Hello User"));
// console.log(chalk.bold("Abhishek"));
// console.log(figlet.textSync("Hello Abhishek"));
console.log(chalk.redBright(figlet.textSync("# Abhishek")));