export const SET_DOCUMENT = 'SET_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const SET_CONTACT = 'SET_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const SET_EDUCATION = 'SET_EDUCATION';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';